/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: esp_audiotest.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "esp_audiotest.pb-c.h"
void   foo__is_open__init
                     (Foo__IsOpen         *message)
{
  static const Foo__IsOpen init_value = FOO__IS_OPEN__INIT;
  *message = init_value;
}
size_t foo__is_open__get_packed_size
                     (const Foo__IsOpen *message)
{
  assert(message->base.descriptor == &foo__is_open__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t foo__is_open__pack
                     (const Foo__IsOpen *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &foo__is_open__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t foo__is_open__pack_to_buffer
                     (const Foo__IsOpen *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &foo__is_open__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Foo__IsOpen *
       foo__is_open__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Foo__IsOpen *)
     protobuf_c_message_unpack (&foo__is_open__descriptor,
                                allocator, len, data);
}
void   foo__is_open__free_unpacked
                     (Foo__IsOpen *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &foo__is_open__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   foo__tips__init
                     (Foo__Tips         *message)
{
  static const Foo__Tips init_value = FOO__TIPS__INIT;
  *message = init_value;
}
size_t foo__tips__get_packed_size
                     (const Foo__Tips *message)
{
  assert(message->base.descriptor == &foo__tips__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t foo__tips__pack
                     (const Foo__Tips *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &foo__tips__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t foo__tips__pack_to_buffer
                     (const Foo__Tips *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &foo__tips__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Foo__Tips *
       foo__tips__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Foo__Tips *)
     protobuf_c_message_unpack (&foo__tips__descriptor,
                                allocator, len, data);
}
void   foo__tips__free_unpacked
                     (Foo__Tips *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &foo__tips__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue foo__is_open__is_open_type__enum_values_by_number[3] =
{
  { "null", "FOO__IS_OPEN__IS_OPEN_TYPE__null", 0 },
  { "open", "FOO__IS_OPEN__IS_OPEN_TYPE__open", 1 },
  { "close", "FOO__IS_OPEN__IS_OPEN_TYPE__close", 2 },
};
static const ProtobufCIntRange foo__is_open__is_open_type__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex foo__is_open__is_open_type__enum_values_by_name[3] =
{
  { "close", 2 },
  { "null", 0 },
  { "open", 1 },
};
const ProtobufCEnumDescriptor foo__is_open__is_open_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "foo.IsOpen.IsOpenType",
  "IsOpenType",
  "Foo__IsOpen__IsOpenType",
  "foo",
  3,
  foo__is_open__is_open_type__enum_values_by_number,
  3,
  foo__is_open__is_open_type__enum_values_by_name,
  1,
  foo__is_open__is_open_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor foo__is_open__field_descriptors[1] =
{
  {
    "isopen_type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Foo__IsOpen, isopen_type),
    &foo__is_open__is_open_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned foo__is_open__field_indices_by_name[] = {
  0,   /* field[0] = isopen_type */
};
static const ProtobufCIntRange foo__is_open__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor foo__is_open__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "foo.IsOpen",
  "IsOpen",
  "Foo__IsOpen",
  "foo",
  sizeof(Foo__IsOpen),
  1,
  foo__is_open__field_descriptors,
  foo__is_open__field_indices_by_name,
  1,  foo__is_open__number_ranges,
  (ProtobufCMessageInit) foo__is_open__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue foo__tips__tips_type__enum_values_by_number[5] =
{
  { "null", "FOO__TIPS__TIPS_TYPE__null", 0 },
  { "open_ok", "FOO__TIPS__TIPS_TYPE__open_ok", 1 },
  { "open_err", "FOO__TIPS__TIPS_TYPE__open_err", 2 },
  { "close_ok", "FOO__TIPS__TIPS_TYPE__close_ok", 3 },
  { "close_err", "FOO__TIPS__TIPS_TYPE__close_err", 4 },
};
static const ProtobufCIntRange foo__tips__tips_type__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex foo__tips__tips_type__enum_values_by_name[5] =
{
  { "close_err", 4 },
  { "close_ok", 3 },
  { "null", 0 },
  { "open_err", 2 },
  { "open_ok", 1 },
};
const ProtobufCEnumDescriptor foo__tips__tips_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "foo.Tips.TipsType",
  "TipsType",
  "Foo__Tips__TipsType",
  "foo",
  5,
  foo__tips__tips_type__enum_values_by_number,
  5,
  foo__tips__tips_type__enum_values_by_name,
  1,
  foo__tips__tips_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor foo__tips__field_descriptors[1] =
{
  {
    "tipstype",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Foo__Tips, tipstype),
    &foo__tips__tips_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned foo__tips__field_indices_by_name[] = {
  0,   /* field[0] = tipstype */
};
static const ProtobufCIntRange foo__tips__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor foo__tips__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "foo.Tips",
  "Tips",
  "Foo__Tips",
  "foo",
  sizeof(Foo__Tips),
  1,
  foo__tips__field_descriptors,
  foo__tips__field_indices_by_name,
  1,  foo__tips__number_ranges,
  (ProtobufCMessageInit) foo__tips__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCMethodDescriptor foo__audio__method_descriptors[1] =
{
  { "AudioTest", &foo__is_open__descriptor, &foo__tips__descriptor },
};
const unsigned foo__audio__method_indices_by_name[] = {
  0         /* AudioTest */
};
const ProtobufCServiceDescriptor foo__audio__descriptor =
{
  PROTOBUF_C__SERVICE_DESCRIPTOR_MAGIC,
  "foo.Audio",
  "Audio",
  "Foo__Audio",
  "foo",
  1,
  foo__audio__method_descriptors,
  foo__audio__method_indices_by_name
};
void foo__audio__audio_test(ProtobufCService *service,
                            const Foo__IsOpen *input,
                            Foo__Tips_Closure closure,
                            void *closure_data)
{
  assert(service->descriptor == &foo__audio__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void foo__audio__init (Foo__Audio_Service *service,
                       Foo__Audio_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &foo__audio__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
